[build]
publish = "public"
functions = "functions"
command = "git submodule update --init --recursive --depth 1 && make non-production-build"

[build.environment]
NODE_VERSION = "17.6.0"
HUGO_VERSION = "0.87.0"

[context.production.environment]
HUGO_BASEURL = "http://run-x.github.io/"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "git submodule update --init --recursive --depth 1 && make deploy-preview"

[context.branch-deploy]
command = "git submodule update --init --recursive --depth 1 && make non-production-build"

#[context.main]
## This context is triggered by the `main` branch and allows search indexing
#publish = "public"
#command = "git submodule update --init --recursive --depth 1 && make production-build"
