name: Installer CI CentOS

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  schedule:
    - cron: '0 1 * * *' # run at 1 AM UTC


jobs:
  centos_latest_install_opta:
    runs-on: ubuntu-latest
    container:
      image: centos:centos7
      env:
        LC_ALL: en_US.UTF-8
        LANG: en_US.UTF-8
        LANGUAGE: en_US.UTF-8
    steps:
      - uses: actions/checkout@v2
      - name: Additional Installations (yum upgrade | install unzip and git)
        run: |
          yum upgrade -y
          yum install -y unzip
          yum install -y git
      - name: Install Opta with Version
        run: |
          cd static
          ./install.sh
      - name: Run Version
        run: $HOME/.opta/opta version
      - name: Run Help
        run: $HOME/.opta/opta --help
  centos_latest_install_opta_w_version:
    runs-on: ubuntu-18.04
    container:
      image: centos:centos7
      env:
        LC_ALL: en_US.UTF-8
        LANG: en_US.UTF-8
        LANGUAGE: en_US.UTF-8
    steps:
      - uses: actions/checkout@v2
      - name: Additional Installations (yum upgrade | install unzip and git)
        run: |
          yum upgrade -y
          yum install -y unzip
          yum install -y git
      - name: Install Opta with Version
        run: |
          cd static
          VERSION="$(curl -s https://dev-runx-opta-binaries.s3.amazonaws.com/latest)" ./install.sh
      - name: Run Version
        run: $HOME/.opta/opta version
      - name: Run Help
        run: $HOME/.opta/opta --help
  centos_latest_install_opta_w_v_version:
    runs-on: ubuntu-18.04
    container:
      image: centos:centos7
    steps:
      - uses: actions/checkout@v2
      - name: Additional Installations (yum upgrade | install unzip and git)
        run: |
          yum upgrade -y
          yum install -y unzip
          yum install -y git
      - name: Install Opta with Version
        run: |
          cd static
          VERSION="v$(curl -s https://dev-runx-opta-binaries.s3.amazonaws.com/latest)" ./install.sh
      - name: Run Version
        run: $HOME/.opta/opta version
      - name: Run Help
        run: $HOME/.opta/opta --help