name: Installer CI Invalid Cases

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  install_opta_invalid_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Opta with Version
        run: |
          cd static
          VERSION=1 ./install.sh
          [[ $? == 1 ]] || exit 1