name: Installer CI Mac

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  mac_latest_install_opta:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Opta with Version
        run: |
          pwd
          cd static
          ./install.sh
      - name: Run Version
        run: /Users/runner/.opta/opta version
      - name: Run Help
        run: /Users/runner/.opta/opta --help
  mac_latest_install_opta_w_version:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Opta with Version
        run: |
          pwd
          cd static
          VERSION=v0.14.7 ./install.sh
      - name: Run Version
        run: /Users/runner/.opta/opta version
      - name: Run Help
        run: /Users/runner/.opta/opta --help
